CREATE SCHEMA "vidaq";

CREATE SCHEMA "accsess_service";

CREATE SCHEMA "playlists_service";

CREATE TABLE "vidaq"."cover_sizes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "size" varchar(20) NOT NULL
);

CREATE TABLE "vidaq"."post_covers" (
  "post_uid" UUID NOT NULL,
  "cover_size_id" int
);

CREATE TABLE "vidaq"."channel_banners" (
  "channel_uid" UUID NOT NULL,
  "cover_size_id" int
);

CREATE TABLE "accsess_service"."user_avatars" (
  "user_uid" UUID NOT NULL,
  "cover_size_id" int
);

CREATE TABLE "playlists_service"."playlist_covers" (
  "playlist_uid" UUID NOT NULL,
  "cover_size_id" int
);

CREATE UNIQUE INDEX "post_covers" ON "vidaq"."post_covers" ("post_uid", "cover_size_id");

CREATE UNIQUE INDEX "channel_banners" ON "vidaq"."channel_banners" ("channel_uid", "cover_size_id");

CREATE UNIQUE INDEX "user_avatars" ON "accsess_service"."user_avatars" ("user_uid", "cover_size_id");

CREATE UNIQUE INDEX "playlist_covers" ON "playlists_service"."playlist_covers" ("playlist_uid", "cover_size_id");

COMMENT ON COLUMN "vidaq"."cover_sizes"."size" IS 'SMALL, MEDIUM, LARGE';

ALTER TABLE "vidaq"."post_covers" ADD FOREIGN KEY ("cover_size_id") REFERENCES "vidaq"."cover_sizes" ("id");

ALTER TABLE "vidaq"."channel_banners" ADD FOREIGN KEY ("cover_size_id") REFERENCES "vidaq"."cover_sizes" ("id");

ALTER TABLE "accsess_service"."user_avatars" ADD FOREIGN KEY ("cover_size_id") REFERENCES "vidaq"."cover_sizes" ("id");

ALTER TABLE "playlists_service"."playlist_covers" ADD FOREIGN KEY ("cover_size_id") REFERENCES "vidaq"."cover_sizes" ("id");

INSERT INTO vidaq.cover_sizes (SIZE) VALUES
('SMALL'), ('MEDIUM'), ('LARGE');
