@startuml

title "Login via Social Network flow"
boundary "Identity Provider" as SN
actor User as U
boundary "Client APP" as GUI
control "access_service" as AC
database "access_service" as DB

autonumber

U-> GUI: Login via Social Network
activate GUI
GUI -> AC: mutation socialNetworkLoginViaAccessToken(socialNetworkType, access_token)

activate AC
AC -> SN: Request user data by socialNetworkType and access_token
activate SN
SN -> AC: email, Social Network Id, Name, Avatar
deactivate SN
alt "if social_network_session for this socialNetworkId already exist"
AC -> GUI: success = true, token, refresh token
GUI -> U: Home page
else "no social_network_session for this socialNetworkId already exist"
AC -> AC: Check if user with such email already exist and\nwas registered via email + password
alt "user with such email already exist"
AC -> DB: create social network session without user_uid
activate DB
DB -> AC: ok
deactivate DB
AC -> GUI: success = true, userCreated = false, socialNetworkType, socialNetworkId, email
deactivate AC
GUI -> U: Merge account request
alt "user accept merge request"
U -> GUI: Accept
GUI -> AC: mutation addSocialNetworkIdToExistedUser(socialNetworkType, socialNetworkId, email)
activate AC
AC -> DB: create user,\nadd user_uid to social network session
activate DB
DB -> AC: ok
deactivate DB
AC -> GUI: success = true, userCreated = true, token, refresh token
deactivate AC
GUI -> U: Let's Vidaq
else "user reject merge request"
U -> GUI: Reject
GUI -> U: Register page
end
else  "user with such email is not exist"
AC -> DB: create social network session with user_uid \ncreate user
activate DB
DB -> AC: ok
deactivate DB
AC -> GUI: success = true, userCreated = true, token, refresh token
deactivate AC
GUI -> U: Let's Vidaq
deactivate GUI
end
end

@enduml