@startuml
title "Authentication flow. To be"

actor User as U
boundary "Client APP" as GUI
control "access_service" as AC

autonumber

U -> GUI: Login request
activate U
activate GUI
GUI -> U: Login page

alt registration
end
U -> GUI: type email or phone
note right GUI
check value format
end note
alt forgot password
end
U -> GUI: type password
GUI -> AC: mutation login
activate AC


alt #Pink no such login & password pair
alt no such login
AC -> GUI: success=false && HTTP 404
end
alt password hashes are not equals
AC -> GUI: success=false && HTTP 403
end
GUI -> U: email not found or password is invalid
else #Technology valid login & password pair

alt #Pink User hit the limits
AC -> GUI: HTTP 429
end

AC -> GUI: success=true && HTTP 200
deactivate AC
GUI -> U: Home page
deactivate GUI
end
deactivate U
@enduml