@startuml
'https://plantuml.com/sequence-diagram
title "Feature toggles (MVP)"

actor User as U
boundary "Client APP" as GUI
control "API" as C

autonumber

==When service start==

C --> C: Get values from env
activate C

...
==When user visit page==

U -> GUI: Visit page with feature toggle
activate GUI

GUI -> GUI: any feature toggles in session storage?

alt "NO feature toggles in session storage"
GUI -> C: getFeatureToggles

alt #Pink "Unsuccessful response"
C --> GUI: success == false
GUI --> U: Render page by default
else #LightGreen "Successful response"
C -> GUI: success == true
deactivate C
GUI -> GUI: Save feature toggles in session storage
end
end

GUI -> U: Apply feature toggles\nand render page
deactivate GUI

@enduml