@startuml
actor User as U
participant App as A
control API as B

title "Forgot password. Mobile Flow. As is"

autonumber

U -> A: Forgot password!
activate U
activate A

A -> U: Restore password page

U -> A: Select type login, type login
A -> B: resetPasswordEmail or resetPasswordMobile
activate B
B --> U: send OTP
U -> A: type new password
A -> A: validate (equals) new password
A <- U: type OTP
A -> B: verifyResetPasswordEmail or verifyResetPasswordMobile
alt valid OTP
B -> A: valid otp
A -> U: lets vidaq
deactivate U
end
alt #Pink Unsuccessful response
B [#Red]-> A: invalid otp
deactivate B
A [#Red]-> A: waiting for OTP code
deactivate A
end

@enduml