@startuml
actor User as U
participant App as GUI
control access_service as AC

title "Forgot password. Mobile Flow. TO BE"
autonumber
U -> GUI: Forgot password!
activate U
activate GUI

GUI -> U: Restore password page

U -> GUI: Select type login, type login
GUI -> AC: mutation resetPasswordEmail or resetPasswordMobile
activate AC
GUI -> U: Restore password page

AC --> U: send OTP
deactivate AC

U -> GUI: type OTP
GUI -> AC: mutation verifyOneTimePassword
activate AC

alt #Pink Unsuccessful response
alt #Pink login is not exist
AC -> GUI: HTTP 404
end

alt #Pink user.state != unverified
AC -> GUI: HTTP 409
end

alt #Pink The limit of registrations per day has been exceeded
AC -> GUI: HTTP 429
end

alt #Pink OTP are not equals or expired
AC -> GUI: HTTP 401
GUI -> GUI: Disable Request OTP button for 60 sec
...
end


else #Technology Successful response
AC -> GUI: HTTP 200
deactivate AC
end


GUI -> U: Restore password page
U -> GUI: Type new password
GUI -> GUI: Validate new password

GUI -> AC: mutation editPassword
note left AC
with auth token
end note
activate AC
AC -> GUI: ok
deactivate AC

GUI -> U: Let's vidaq
deactivate GUI
deactivate U
@enduml