@startuml
actor User as U
participant App as GUI
control access_service as AC

title "Forgot password. TO BE"
autonumber
U -> GUI: forgot password!
activate U
activate GUI

GUI -> U: recover password page

U -> GUI: select type login, input login
GUI -> AC: mutation resetPasswordEmail or resetPasswordMobile
activate AC
alt #Pink Unsuccessful response

alt #Pink Bad formed request
AC -> GUI: HTTP 400
end

alt #Pink User does not exist
AC -> GUI: HTTP 404
end

alt #Pink The limit attempt account recovery per day has been exceeded
AC -> GUI: HTTP 429
end

else #Technology Successful response
AC --> U: send OTP
AC -> GUI: HTTP 200
deactivate AC
end
GUI -> U: recover password page


U -> GUI: type OTP
GUI -> AC: mutation verifyOneTimePassword
activate AC

alt #Pink Unsuccessful response
alt #Pink User does not exist
AC -> GUI: HTTP 404
end

alt #Pink user.state != unverified
AC -> GUI: HTTP 409
end

alt #Pink The limit of registrations per day has been exceeded
AC -> GUI: HTTP 429
GUI -> GUI: Disable Request OTP button for {retryAfter} sec
end

alt #Pink OTP are not equals or expired
AC -> GUI: HTTP 401
GUI -> GUI: Disable Request OTP button for 60 sec
...
end


else #Technology Successful response
AC -> GUI: HTTP 200
deactivate AC
end


GUI -> U: restore password page
U -> GUI: type new password
GUI -> GUI: validate new password

GUI -> AC: mutation editPassword
note left AC
with auth token
end note
activate AC

alt #Pink Unsuccessful response

alt #Pink The password does not strong enough
AC -> GUI: HTTP 422
end

alt #Pink Forbidden
AC -> GUI: HTTP 403
end


else #Technology Successful response
AC -> GUI: ok
deactivate AC
end

GUI -> U: Let's vidaq
deactivate GUI
deactivate U
@enduml