@startuml
actor User as U
participant App as A
control access_service as B

title "Forgot password. Mobile Flow. TO BE"
autonumber
U -> A: Forgot password!
activate U
activate A

A -> U: Restore password page

U -> A: Select type login, type login
A -> B: mutation resetPasswordEmail or resetPasswordMobile
activate B
A -> U: Restore password page

B --> U: send OTP
deactivate B

U -> A: type OTP
A -> B: mutation verifyOneTimePassword
activate B

alt #Pink Unsuccessful response

alt #Pink bad formed request
A <- B: HTTP 400
end

alt #Pink login is not exist
A <- B: HTTP 404
end

alt #Pink Incorrect OTP code
B [#Red]-> A: HTTP 401
A [#Red]-> A: Disable Request OTP button for 60 sec
...
U [#Red]-> A: Request another OTP\n(mutation resetPasswordEmail or resetPasswordMobile)
A [#Red]-> U:  Type OTP password page
end

alt #Pink Limit of new code requests per day has been exceeded
B [#Red]-> A: HTTP 429
A -> A: Disable Request OTP button for {failure.retryAfter}
end
else #Technology Successful response
B -> A: valid OTP
deactivate B
end


A -> U: Restore password page
U -> A: Type new password
A -> A: Validate new password

A -> B: mutation editPassword
note left B
with auth token
end note
activate B
B -> A: ok
deactivate B

A -> U: Let's vidaq
deactivate A
deactivate U
@enduml