@startuml
actor User as U
participant App as A
control API as B

title "Forgot password. Mobile Flow. TO BE"
autonumber
U -> A: Forgot password!
activate U
activate A

A -> U: Restore password page

U -> A: Select type login, type login
A -> B: resetPasswordEmail or resetPasswordMobile
activate B
A -> U: Restore password page

B --> U: send OTP
deactivate B

U -> A: type OTP
A -> B: verifyOneTimePassword
activate B
alt valid OTP
B -> A: valid OTP
deactivate B

A -> U: Restore password page
U -> A: Type new password
A -> A: Validate new password

A -> B: editPassword
activate B
B -> A: ok
end
alt #Pink Unsuccessful response
B [#Red]-> A: Invalid OTP
deactivate B
alt #Pink HTTP 401 - Incorrect OTP code
A [#Red]-> A: Disable Request OTP button for 60 sec
...
U [#Red]-> A: Request another OTP\n(resetPasswordEmail or resetPasswordMobile)
A [#Red]-> U:  Restore password page
end
...
alt #Pink HTTP 429 - Limit of new code requests per day has been exceeded
A -> A: Disable Request OTP button for {failure.retryAfter}
end
end
deactivate A
deactivate U
@enduml