@startuml
'https://plantuml.com/sequence-diagram
title "Getting image flow. To be"

actor User as U
boundary "Client APP" as GUI
control "api-service" as AS
control "vidaq-service" as V
collections "nginx" as WS


autonumber

U -> GUI: Переход на главную страницу
activate GUI

GUI -> AS: getPosts
activate AS
note left AS
Получаем список постов,
где PostType.cover - путь до
нормализованного файла.
{host} часть пути подставляет API
end note
AS -> V: GET posts/
activate V
V -> AS: http 200
deactivate V
AS -> GUI: success == true
deactivate AS

GUI -> WS: GET {host}/{image_name}
activate WS
alt #LightBlue "Изобр-е с указанными \nпараметрами отсутствует кэше"
WS -> WS: Получаем \nнормализованное \nизображение
WS -> WS: Применяем \nпреобразования
WS -> WS: Сохранияем в кэш
end alt

WS -> GUI: image
deactivate WS


GUI -> U:
deactivate GUI

@enduml