@startuml
'https://plantuml.com/sequence-diagram
title "Upload image flow. AS IS"

actor User as U
boundary "Client APP" as GUI
control "api-service" as AS
control "uploader-service" as US


autonumber

U -> GUI: Загрузить аватар
activate GUI
GUI -> AS: uploadLogoByChannelUid
activate AS
note left AS
%autonumber%. Аналогично
uploadCoverByPostUid
uploadBannerByChannelUid
uploadCoverByPlaylistUid
uploadAvatar

end note

AS -> US: POST /channel-logo/{channel_uid}
activate US
note left US
%autonumber%. Аналогично
POST /images/avatar
POST /video-cover/{post_uid}
POST /channel-banner/{channel_uid}
POST /playlist-cover/{playlist_uid}
end note

US -> US: update image path

US -> AS:
deactivate US
AS -> GUI: success = true
deactivate AS

GUI -> U:
deactivate GUI

@enduml