@startuml

title "Registration flow. As is"

actor User as U
boundary "Client APP" as GUI
control "access_service" as AC
database "access_service" as DB

autonumber

U -> GUI: registration request
activate U
activate GUI
GUI -> U: registration page
U -> GUI: type login & email
GUI -> AC: mutation registerEmail or registerMobile
activate AC
AC -> DB: check login
activate DB
alt #Technology login is already exist
AC <- DB: user
deactivate DB
alt #Pink user.state != unverified
AC -> AC: user.state != unverified
AC -> GUI: HTTP 409
else #Technology user.state == unverified
AC -> DB: check user verifications
activate DB
alt #Technology has unfinished verifications
AC <- DB: user verifications list
deactivate DB
AC -> DB: update user
activate DB
AC <- DB: ok
deactivate DB
end
end 
else #Business login is not exist
DB -> AC: null


AC -> DB: create user
activate DB

AC <- DB: user
note left DB
unverified user
end note
deactivate DB
end
AC -> DB: create new OTP
activate DB
note left DB
consumed = False
end note
AC <- DB: OTP
deactivate DB
AC --> U: OTP
AC -> GUI: HTTP 200
deactivate AC


GUI -> U: OTP page
U -> GUI: type OTP
GUI -> AC: mutation verifyEmail or verifyMobile
activate AC
AC -> DB: check login
activate DB

alt #Pink login is not exist
DB -> AC: null
AC -> GUI: HTTP 404
else #Technology login is already exist
AC <- DB: user
deactivate DB

alt #Pink user.state != unverified
AC -> AC: user.state != unverified
AC -> GUI: HTTP 409
else #Technology user.state == unverified
AC -> DB: check user verifications
activate DB
alt #Technology has unfinished verifications
AC <- DB: user verifications list
deactivate DB
alt #Pink OTP are not equals or expired
AC -> GUI: HTTP 401
end
AC -> DB: OTP consumed = True, user.state = ACTIVE
activate DB
DB -> AC: user
deactivate DB


AC -> DB: create token, refreshToken
activate DB
DB -> AC: token, refreshToken
deactivate DB
AC -> GUI: HTTP 200
deactivate AC
deactivate GUI
end
end 
end
deactivate U
@enduml