@startuml

title "Registration flow. TO BE"

actor User as U
boundary "Client APP" as GUI
control "access_service" as AC

autonumber

U -> GUI: registration request
activate U
activate GUI
GUI -> U: registration page
U -> GUI: type login & email
GUI -> AC: mutation registerEmail or registerMobile
activate AC


alt #Pink Unsuccessful response

alt #Pink bad formed request
AC -> GUI: HTTP 400
end

alt #Pink user.state != unverified
AC -> GUI: HTTP 409
end

alt #Pink The limit of registrations per day has been exceeded
AC -> GUI: HTTP 429
end

else #Technology Successful response
AC --> U: OTP
AC -> GUI: HTTP 200
deactivate AC

GUI -> U: OTP page
end

U -> GUI: type OTP
GUI -> AC: mutation verifyOneTimePassword
activate AC

alt #Pink Unsuccessful response
alt #Pink login is not exist
AC -> GUI: HTTP 404
end

alt #Pink user.state != unverified
AC -> GUI: HTTP 409
end

alt #Pink The limit of registrations per day has been exceeded
AC -> GUI: HTTP 429
GUI -> GUI: Disable Request OTP button for {retryAfter} sec
end

alt #Pink OTP are not equals or expired
AC -> GUI: HTTP 401
GUI -> GUI: Disable Request OTP button for 60 sec
...
end


else #Technology Successful response
AC -> GUI: HTTP 200
deactivate AC
end

GUI -> U: Let's vidaq
deactivate GUI
deactivate U

@enduml