@startuml
'https://plantuml.com/sequence-diagram
title "Post video flow. AS IS"

actor User as U
boundary "Client APP" as GUI
control "API" as C

autonumber

U -> GUI: Upload video
activate U
activate GUI
GUI -> C: query getChannels
activate C

note left C
Получить информацию о пользовательских каналах
end note

C -> GUI: ok, http 200
deactivate C
GUI -> U: Окно/страница загрузки видео
alt "У пользователя больше одного активного канала"
GUI -> U: Список каналов пользователя
U -> GUI: Выбор канала
else "У пользователя только один активный канал"
GUI -> GUI: Select channel
else "У пользователя нет активных каналов"
U -> GUI: Название канала
GUI -> C: mutation createChannel
activate C
note left C
Создаем канал
end note

C -> GUI: ok, http 200
deactivate  C
end

GUI -> C: mutation loginChannel
activate C
note left C
Получаем токен канала
end note
C -> GUI: ok, http 200
deactivate C

U --> GUI: Выбор видео
GUI -> C: mutation createPost
activate C
note left C
Загружаем видео (создаем пост)
end note
C -> GUI: ok, http 200
deactivate C
GUI -> U: Страница описания поста

U -> GUI: Добавить описание поста
GUI -> C: mutation updatePost
activate C
note left C
Обновляем пост
end note
C -> GUI: ok, http 200
deactivate C

GUI -> U: Страница со списком постов канала
deactivate GUI
@enduml